from turtle import *
speed(0)
up()
goto(-300,100)
down()
color('blue', '#10c6eb')
begin_fill()
for i in range(4):
    fd(200)
    lt(90)
end_fill()
up()
goto(300, 100)
down()
print('test')
color('green', 'yellow')
begin_fill()
circle(100)
end_fill()
c = textinput("?", "what color?")
# r = int(textinput("?", "what size?"))
r = numinput("?", "what size?")
x = numinput("X", "Enter x?")
y = numinput("Y", "Enter y?")
up()
goto(x,y)
down()
color(c, c)
begin_fill()
circle(r)
end_fill()
mainloop()